services:
  backend:
    build: ./backend
    container_name: lucas-ssh-backend
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER_READONLY}
      DB_PASSWORD: ${DB_PASSWORD_READONLY}
      MAIL_API_KEY: ${MAIL_API_KEY}
      MAIL_SECRET_KEY: ${MAIL_SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    volumes:
      - ./backend:/app
    ports:
      - "8002:8002"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8002
      
  frontend:
    build: ./frontend
    container_name: lucas-ssh-frontend
    environment:
      - VITE_BACKEND_URL=${BACKEND_URL}
      - VITE_FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    ports:
      - "5173:5173"
      - "7002:7002"

  redis:
    image: redis
    container_name: lucas-ssh-redis

  apigateway:
    image: nginx
    container_name: lucas-ssh-apigateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:80"

  db:
    image: postgres
    container_name: lucas-ssh-db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD_READONLY}
      POSTGRES_USER: ${DB_USER_READONLY}
    volumes:
      - ./backend/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    
  db-adminer:
    image: adminer
    container_name: lucas-ssh-db-adminer
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
  