name: Frontend Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-frontend:
    name: Run Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Goto frontend and run tests
        run: cd frontend && npm i && npm test
